spring:
  application:
    name: redis

  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/testdb
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop


  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000